************* Module sharednotes
sharednotes\__init__.py:1:0: E5110: Django was not configured. For more information run pylint --load-plugins=pylint_django --help-msg=django-not-configured (django-not-configured)
************* Module sharednotes.api.views
sharednotes\api\views.py:167:11: W0718: Catching too general exception Exception (broad-exception-caught)
sharednotes\api\views.py:163:32: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
sharednotes\api\views.py:157:19: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)

------------------------------------------------------------------
Your code has been rated at 9.50/10 (previous run: 9.50/10, +0.00)

